version: '3.8'

services:
  broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: iot_backend
    depends_on:
      - broker
    volumes:
      - ./data:/app/data
    restart: always
    # No se expone puerto ya que el proxy se encargará

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: iot_dashboard
    # Eliminamos el mapeo de puertos para que no compita
    volumes:
      - ./data:/app/data
    depends_on:
      - backend
    restart: always

  camera:
    build:
      context: ./mjpg-streamer
      dockerfile: Dockerfile
    container_name: mjpg_streamer
    devices:
      - "/dev/video0:/dev/video0"
    ports:
      - "8080:8080"
    restart: always

  proxy:
    image: nginx:latest
    container_name: iot_proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "5000:80"
    depends_on:
      - backend
      - dashboard
      - camera
    restart: always

volumes:
  mosquitto_data:
