version: '3.8'

services:
  broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: iot_backend
    depends_on:
      - broker
    volumes:
      - ./data:/app/data
    restart: always
  
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: iot_dashboard
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    depends_on:
      - backend
    restart: always

volumes:
  mosquitto_data:
