version: '3.8'

services:
  broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: iot_backend
    depends_on:
      - broker
    restart: always

volumes:
  mosquitto_data:
